import 'package:flutter/material.dart';

IconData iconFromName(String? name) {
  return switch (name) {
    'restaurant' => Icons.restaurant_rounded,
    'local_cafe' => Icons.local_cafe_rounded,
    'fastfood' => Icons.fastfood_rounded,
    'bakery_dining' => Icons.bakery_dining_rounded,
    'icecream' => Icons.icecream_rounded,
    'lunch_dining' => Icons.lunch_dining_rounded,
    'flight' => Icons.flight_rounded,
    'hotel' => Icons.hotel_rounded,
    'attractions' => Icons.attractions_rounded,
    'local_airport' => Icons.local_airport_rounded,
    'directions_bus' => Icons.directions_bus_rounded,
    'train' => Icons.train_rounded,
    'card_travel' => Icons.card_travel_rounded,
    'car_rental' => Icons.car_rental_rounded,
    'school' => Icons.school_rounded,
    'account_balance' => Icons.account_balance_rounded,
    'model_training' => Icons.model_training_rounded,
    'local_library' => Icons.local_library_rounded,
    'menu_book' => Icons.menu_book_rounded,
    'health_and_safety' => Icons.health_and_safety_rounded,
    'local_hospital' => Icons.local_hospital_rounded,
    'medical_services' => Icons.medical_services_rounded,
    'local_pharmacy' => Icons.local_pharmacy_rounded,
    'shopping_bag' => Icons.shopping_bag_rounded,
    'local_mall' => Icons.local_mall_rounded,
    'local_grocery_store' => Icons.local_grocery_store_rounded,
    'shopping_cart' => Icons.shopping_cart_rounded,
    'checkroom' => Icons.checkroom_rounded,
    'devices' => Icons.devices_rounded,
    'store' => Icons.store_rounded,
    'handyman' => Icons.handyman_rounded,
    'atm' => Icons.atm_rounded,
    'content_cut' => Icons.content_cut_rounded,
    'car_repair' => Icons.car_repair_rounded,
    'build' => Icons.build_rounded,
    'local_laundry_service' => Icons.local_laundry_service_rounded,
    'local_post_office' => Icons.local_post_office_rounded,
    'movie' => Icons.movie_rounded,
    'park' => Icons.park_rounded,
    'museum' => Icons.museum_rounded,
    'sports_esports' => Icons.sports_esports_rounded,
    'sports_soccer' => Icons.sports_soccer_rounded,
    'theater_comedy' => Icons.theater_comedy_rounded,
    'local_gas_station' => Icons.local_gas_station_rounded,
    'place' => Icons.place_rounded,
    _ => Icons.place_outlined,
  };
}
